version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - mynetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_DB=test

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:
